pom:
  propertiesFileName: properties-pom.yaml

logging:
  level:
    root: info
    com.anst.sd.api: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/
  jpa:
    hibernate:
      ddl-auto: update
  server:
    error:
      include-message: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    out-of-order: true
  data:
    redis:
      url: redis://localhost:6379
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/user?authSource=admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: tgConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

security:
  jwt:
    block-valid-access: true
    storage: accessStorage
    access:
      secret: accessSecret
      expiration: 10m
    refresh:
      secret: refreshSecret
      expiration: 168h

pageable:
  size: 20