pom:
  propertiesFileName: properties-pom.yaml

logging:
  level:
    root: info
    com.anst.sd.api: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres:5432/
  jpa:
    hibernate:
      ddl-auto: update
  server:
    error:
      include-message: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  data:
    redis:
      url: redis://redis:6379

security:
  jwt:
    block-valid-access: true
    storage: accessStorage
    access:
      secret: accessSecret
      expiration: 10m
    refresh:
      secret: refreshSecret
      expiration: 168h

pageable:
  size: 20