logging:
  level:
    root: info
    com.anst.sd.api: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
  server:
    error:
      include-message: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  data:
    redis:
      url: ${REDIS_URL}
    mongodb:
      uri: ${MONGO_URL_USER}
  kafka:
    path: ${KAFKA_URL}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer

    bootstrap-servers: ${KAFKA_URL}

security:
  code:
    expiration-time: 20
    return: true
  jwt:
    block-valid-access: true
    storage: ${JWT_ACCESS_STORAGE}
    access:
      secret: ${JWT_ACCESS_SECRET}
      expiration: 15m
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      expiration: 168h

settings:
  dev-mode: true

shedlock:
  default-lock-at-most-for: 30s
  notification-sending:
    execution-delay: 5000
    lock-at-least-for: 1s
    lock-at-most-for: 4s

service:
  telegram-bot:
    api:
      url: ${SERVICE_TELEGRAM_BOT_API_URL}

pageable:
  size: 20