logging:
  level:
    root: info
    com.anst.sd.api: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    error:
      include-message: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    out-of-order: true
  data:
    redis:
      url: redis://localhost:6379
    mongodb:
      uri: ${MONGO_URL_USER}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092

security:
  code:
    expiration-time: 180
    return: true
  jwt:
    block-valid-access: true
    storage: accessStorage
    access:
      secret: accessSecret
      expiration: 10m
    refresh:
      secret: refreshSecret
      expiration: 168h

settings:
  dev-mode: true

shedlock:
  default-lock-at-most-for: 30s
  notification-sending:
    execution-delay: 5000
    lock-at-least-for: 1s
    lock-at-most-for: 4s

service:
  telegram-bot:
    api:
      url: https://localhost:8889 #url сервиса telegram-bot или заглушки. Нужно указать

pageable:
  size: 20