pom:
  propertiesFileName: properties-pom.yaml

logging:
  level:
    root: info
    com.example.todolistcoursework: DEBUG

server:
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_USERNAME}
    username: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
  server:
    error:
      include-message: always
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  data:
    redis:
      url: ${REDIS_URL}

security:
  jwt:
    block-valid-access: true
    storage: ${JWT_ACCESS_STORAGE}
    access:
      secret: ${JWT_ACCESS_SECRET}
      expiration: 10m
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      expiration: 168h

pageable:
  size: 20